version: '3.8'

services:
  php:
    build: .
    image: php:8.2-apache
    container_name: php-app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db-hrms
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hrms2025
      MYSQL_DATABASE: hrms
      MYSQL_USER: user
      MYSQL_PASSWORD: hrms2025
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-hrms
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: hrms2025
